export const products = [
  {
    id: 1,
    name: "NVIDIA GeForce RTX 4070",
    description: "GPU para gaming 1440p, ray tracing y creacion de contenido.",
    price: 599,
    category: "GPU",
    image: "https://placehold.co/800x600/14213d/fca311?text=RTX+4070",
    stock: 8,
  },
  {
    id: 2,
    name: "AMD Ryzen 7 7700X",
    description: "Procesador AM5 de 8 nucleos con gran rendimiento por watt.",
    price: 329,
    category: "CPU",
    image: "https://placehold.co/800x600/1b4332/95d5b2?text=Ryzen+7",
    stock: 12,
  },
  {
    id: 3,
    name: "Kingston Fury 32GB DDR5",
    description: "Kit dual channel DDR5 ideal para gaming y multitarea.",
    price: 129,
    category: "RAM",
    image: "https://placehold.co/800x600/2b2d42/edf2f4?text=32GB+DDR5",
    stock: 20,
  },
  {
    id: 4,
    name: "Samsung 980 Pro 1TB",
    description: "SSD NVMe PCIe 4.0 rapido para sistema, juegos y proyectos.",
    price: 89,
    category: "Storage",
    image: "https://placehold.co/800x600/003566/ffc300?text=980+Pro",
    stock: 16,
  },
  {
    id: 5,
    name: "ASUS ROG B650",
    description: "Motherboard AM5 con DDR5, PCIe 4.0 y conectividad moderna.",
    price: 249,
    category: "Motherboard",
    image: "https://placehold.co/800x600/370617/ffba08?text=ROG+B650",
    stock: 6,
  },
  {
    id: 6,
    name: "Corsair RM850x",
    description: "Fuente 80+ Gold modular con potencia para GPUs actuales.",
    price: 139,
    category: "PSU",
    image: "https://placehold.co/800x600/212529/f8f9fa?text=RM850x",
    stock: 10,
  },
  {
    id: 7,
    name: "NZXT H5 Flow",
    description: "Gabinete ATX con excelente flujo de aire y montaje limpio.",
    price: 94,
    category: "Case",
    image: "https://placehold.co/800x600/264653/e9c46a?text=H5+Flow",
    stock: 9,
  },
  {
    id: 8,
    name: "DeepCool AK620",
    description: "Disipador de doble torre para CPUs de alto rendimiento.",
    price: 64,
    category: "Cooling",
    image: "https://placehold.co/800x600/343a40/ced4da?text=AK620",
    stock: 14,
  },
]

export const builderCategories = ["CPU", "Motherboard", "RAM", "GPU", "Storage", "PSU", "Case", "Cooling"]
